### ISSUE TITLE
Failed to change lights

### ISSUE THREAD

**Issue by Lxrits** [muckelba/dynamic-lights-homeassistant#5]
Home assistant instanse accessable from domain with valid ssl certificate. I can use webhook via public internet. But extension throws this error on console and idk what to do with this.

![image](https://github.com/user-attachments/assets/f30c9292-c6bf-42d0-a0e9-7259dfa18cea)

**Comment by muckelba** [comment]
I had that issue in the past, but it was caused by a mistyped domain name.

If you are sure that the domain is correct, maybe try to allow `https://xpui.app.spotify.com` in the HTTP settings of homeassistant:
```yaml
http:
  cors_allowed_origins:
    - https://xpui.app.spotify.com
```
